package com.bys.ots.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import com.bys.ots.model.DnInfoE1;
import com.bys.ots.model.DnInfoE1Key;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DnInfoE1Mapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dn_info_e1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DnInfoE1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dn_info_e1
     *
     * @mbg.generated
     */
    int insert(DnInfoE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dn_info_e1
     *
     * @mbg.generated
     */
    int insertSelective(DnInfoE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dn_info_e1
     *
     * @mbg.generated
     */
    DnInfoE1 selectByPrimaryKey(DnInfoE1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dn_info_e1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DnInfoE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dn_info_e1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DnInfoE1 record);

    int insertBatch(List<DnInfoE1> data);

    DnInfoE1 selectBySO(@Param("so") String SO);

    DnInfoE1 selectBySOAndItem(@Param("so") String so, @Param("soItem") String soItem);
}