/**
 * E1email dao层
 */
package com.bys.ots.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.bys.ots.model.SoEmailE1;
import com.bys.ots.model.SoEmailE1Key;

/**
 * @author wanggang
 * 2019/12/02
 */

@Mapper
public interface SoEmailE1Mapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_email_e1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SoEmailE1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_email_e1
     *
     * @mbg.generated
     */
    int insert(SoEmailE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_email_e1
     *
     * @mbg.generated
     */
    int insertSelective(SoEmailE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_email_e1
     *
     * @mbg.generated
     */
    SoEmailE1 selectByPrimaryKey(SoEmailE1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_email_e1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SoEmailE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_email_e1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SoEmailE1 record);

    int insertBatch(List<SoEmailE1> data);

    List<SoEmailE1> selectByEmail(String email);
}