package com.bys.ots.dao;

import com.bys.ots.model.SoInfo;
import com.bys.ots.model.SoInfoItem;
import com.bys.ots.model.SoInfoSap;
import com.bys.ots.model.SoInfoSapKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SoInfoSapMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_sap
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SoInfoSapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_sap
     *
     * @mbg.generated
     */
    int insert(SoInfoSap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_sap
     *
     * @mbg.generated
     */
    int insertSelective(SoInfoSap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_sap
     *
     * @mbg.generated
     */
    SoInfoSap selectByPrimaryKey(SoInfoSapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_sap
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SoInfoSap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_sap
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SoInfoSap record);

    SoInfo selectBySOAndItem(@Param("so") String so, @Param("soItem") String soItem);

    SoInfo selectBySO(@Param("so") String so);
}