/**
 * E1用户信息dao层
 */
package com.bys.ots.dao;

import java.util.List;

import com.bys.ots.model.OrderListResponse;
import com.bys.ots.model.SoInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.bys.ots.model.SoInfoE1;
import com.bys.ots.model.SoInfoE1Key;

/**
 * @author wanggang
 * 2019/12/02
 */

@Mapper
public interface SoInfoE1Mapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_e1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SoInfoE1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_e1
     *
     * @mbg.generated
     */
    int insert(SoInfoE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_e1
     *
     * @mbg.generated
     */
    int insertSelective(SoInfoE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_e1
     *
     * @mbg.generated
     */
    SoInfoE1 selectByPrimaryKey(SoInfoE1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_e1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SoInfoE1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_info_e1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SoInfoE1 record);

    int insertBatch(List<SoInfoE1> data);

    SoInfoE1 selectBySO(@Param("so") String so);

    List<SoInfo> selectByEmailAndStatus(@Param("email") String email,
                                        @Param("deliveryStatus") String deliveryStatus);
}