package com.bys.ots.model;

public class DnInfoE1Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.DN
     *
     * @mbg.generated
     */
    private String dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.DN_Item
     *
     * @mbg.generated
     */
    private String dnItem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.DN
     *
     * @return the value of dn_info_e1.DN
     *
     * @mbg.generated
     */
    public String getDn() {
        return dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.DN
     *
     * @param dn the value for dn_info_e1.DN
     *
     * @mbg.generated
     */
    public void setDn(String dn) {
        this.dn = dn == null ? null : dn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.DN_Item
     *
     * @return the value of dn_info_e1.DN_Item
     *
     * @mbg.generated
     */
    public String getDnItem() {
        return dnItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.DN_Item
     *
     * @param dnItem the value for dn_info_e1.DN_Item
     *
     * @mbg.generated
     */
    public void setDnItem(String dnItem) {
        this.dnItem = dnItem == null ? null : dnItem.trim();
    }
}