package com.bys.ots.model;

import java.util.Date;

public class DnInfoE1 extends DnInfoE1Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.SO
     *
     * @mbg.generated
     */
    private String so;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.SO_Item
     *
     * @mbg.generated
     */
    private String soItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.Plant
     *
     * @mbg.generated
     */
    private String plant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.Stor_Loc
     *
     * @mbg.generated
     */
    private String storLoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.Shipping_Point
     *
     * @mbg.generated
     */
    private String shippingPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.DN_status
     *
     * @mbg.generated
     */
    private Integer dnStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.Delivery_Date
     *
     * @mbg.generated
     */
    private Date deliveryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.Qty
     *
     * @mbg.generated
     */
    private Integer qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dn_info_e1.Unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.SO
     *
     * @return the value of dn_info_e1.SO
     *
     * @mbg.generated
     */
    public String getSo() {
        return so;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.SO
     *
     * @param so the value for dn_info_e1.SO
     *
     * @mbg.generated
     */
    public void setSo(String so) {
        this.so = so == null ? null : so.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.SO_Item
     *
     * @return the value of dn_info_e1.SO_Item
     *
     * @mbg.generated
     */
    public String getSoItem() {
        return soItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.SO_Item
     *
     * @param soItem the value for dn_info_e1.SO_Item
     *
     * @mbg.generated
     */
    public void setSoItem(String soItem) {
        this.soItem = soItem == null ? null : soItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.Plant
     *
     * @return the value of dn_info_e1.Plant
     *
     * @mbg.generated
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.Plant
     *
     * @param plant the value for dn_info_e1.Plant
     *
     * @mbg.generated
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.Stor_Loc
     *
     * @return the value of dn_info_e1.Stor_Loc
     *
     * @mbg.generated
     */
    public String getStorLoc() {
        return storLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.Stor_Loc
     *
     * @param storLoc the value for dn_info_e1.Stor_Loc
     *
     * @mbg.generated
     */
    public void setStorLoc(String storLoc) {
        this.storLoc = storLoc == null ? null : storLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.Shipping_Point
     *
     * @return the value of dn_info_e1.Shipping_Point
     *
     * @mbg.generated
     */
    public String getShippingPoint() {
        return shippingPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.Shipping_Point
     *
     * @param shippingPoint the value for dn_info_e1.Shipping_Point
     *
     * @mbg.generated
     */
    public void setShippingPoint(String shippingPoint) {
        this.shippingPoint = shippingPoint == null ? null : shippingPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.DN_status
     *
     * @return the value of dn_info_e1.DN_status
     *
     * @mbg.generated
     */
    public Integer getDnStatus() {
        return dnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.DN_status
     *
     * @param dnStatus the value for dn_info_e1.DN_status
     *
     * @mbg.generated
     */
    public void setDnStatus(Integer dnStatus) {
        this.dnStatus = dnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.Delivery_Date
     *
     * @return the value of dn_info_e1.Delivery_Date
     *
     * @mbg.generated
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.Delivery_Date
     *
     * @param deliveryDate the value for dn_info_e1.Delivery_Date
     *
     * @mbg.generated
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.Qty
     *
     * @return the value of dn_info_e1.Qty
     *
     * @mbg.generated
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.Qty
     *
     * @param qty the value for dn_info_e1.Qty
     *
     * @mbg.generated
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dn_info_e1.Unit
     *
     * @return the value of dn_info_e1.Unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dn_info_e1.Unit
     *
     * @param unit the value for dn_info_e1.Unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}