package com.bys.ots.model;

public class SoEmailE1Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_email_e1.SO
     *
     * @mbg.generated
     */
    private String so;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_email_e1.SO_Item
     *
     * @mbg.generated
     */
    private String soItem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_email_e1.SO
     *
     * @return the value of so_email_e1.SO
     *
     * @mbg.generated
     */
    public String getSo() {
        return so;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_email_e1.SO
     *
     * @param so the value for so_email_e1.SO
     *
     * @mbg.generated
     */
    public void setSo(String so) {
        this.so = so == null ? null : so.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_email_e1.SO_Item
     *
     * @return the value of so_email_e1.SO_Item
     *
     * @mbg.generated
     */
    public String getSoItem() {
        return soItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_email_e1.SO_Item
     *
     * @param soItem the value for so_email_e1.SO_Item
     *
     * @mbg.generated
     */
    public void setSoItem(String soItem) {
        this.soItem = soItem == null ? null : soItem.trim();
    }
}