package com.bys.ots.model;

import java.util.Date;

public class SoInfoSap extends SoInfoSapKey
{
    public SoInfoSap(String so, String soItem)
    {
        super(so, soItem);
        // TODO Auto-generated constructor stub
    }

    public SoInfoSap()
    {
        super();
        // TODO Auto-generated constructor stub
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.po_number
     *
     * @mbg.generated
     */
    private String poNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.soldTo_code
     *
     * @mbg.generated
     */
    private String soldtoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.soldTo_name
     *
     * @mbg.generated
     */
    private String soldtoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.shipTo_code
     *
     * @mbg.generated
     */
    private String shiptoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.shipTo_name
     *
     * @mbg.generated
     */
    private String shiptoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.so_createDate
     *
     * @mbg.generated
     */
    private Date soCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sale_org
     *
     * @mbg.generated
     */
    private String saleOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.dis_c
     *
     * @mbg.generated
     */
    private String disC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sale_office
     *
     * @mbg.generated
     */
    private String saleOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.so_overall_status
     *
     * @mbg.generated
     */
    private String soOverallStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.delivery_status
     *
     * @mbg.generated
     */
    private String deliveryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.billing_status
     *
     * @mbg.generated
     */
    private String billingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sku
     *
     * @mbg.generated
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.qty
     *
     * @mbg.generated
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sale_personName
     *
     * @mbg.generated
     */
    private String salePersonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sale_personPhone
     *
     * @mbg.generated
     */
    private String salePersonphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sale_personEmail
     *
     * @mbg.generated
     */
    private String salePersonemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sap_CreateBy
     *
     * @mbg.generated
     */
    private String sapCreateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sap_CreaterName
     *
     * @mbg.generated
     */
    private String sapCreatername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sap_CreaterTelephone
     *
     * @mbg.generated
     */
    private String sapCreatertelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_sap.sap_CreaterEmail
     *
     * @mbg.generated
     */
    private String sapCreateremail;

    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.po_number
     *
     * @return the value of so_info_sap.po_number
     * @mbg.generated
     */
    public String getPoNumber()
    {
        return poNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.po_number
     *
     * @param poNumber the value for so_info_sap.po_number
     * @mbg.generated
     */
    public void setPoNumber(String poNumber)
    {
        this.poNumber = poNumber == null ? null : poNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.soldTo_code
     *
     * @return the value of so_info_sap.soldTo_code
     * @mbg.generated
     */
    public String getSoldtoCode()
    {
        return soldtoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.soldTo_code
     *
     * @param soldtoCode the value for so_info_sap.soldTo_code
     * @mbg.generated
     */
    public void setSoldtoCode(String soldtoCode)
    {
        this.soldtoCode = soldtoCode == null ? null : soldtoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.soldTo_name
     *
     * @return the value of so_info_sap.soldTo_name
     * @mbg.generated
     */
    public String getSoldtoName()
    {
        return soldtoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.soldTo_name
     *
     * @param soldtoName the value for so_info_sap.soldTo_name
     * @mbg.generated
     */
    public void setSoldtoName(String soldtoName)
    {
        this.soldtoName = soldtoName == null ? null : soldtoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.shipTo_code
     *
     * @return the value of so_info_sap.shipTo_code
     * @mbg.generated
     */
    public String getShiptoCode()
    {
        return shiptoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.shipTo_code
     *
     * @param shiptoCode the value for so_info_sap.shipTo_code
     * @mbg.generated
     */
    public void setShiptoCode(String shiptoCode)
    {
        this.shiptoCode = shiptoCode == null ? null : shiptoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.shipTo_name
     *
     * @return the value of so_info_sap.shipTo_name
     * @mbg.generated
     */
    public String getShiptoName()
    {
        return shiptoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.shipTo_name
     *
     * @param shiptoName the value for so_info_sap.shipTo_name
     * @mbg.generated
     */
    public void setShiptoName(String shiptoName)
    {
        this.shiptoName = shiptoName == null ? null : shiptoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.so_createDate
     *
     * @return the value of so_info_sap.so_createDate
     * @mbg.generated
     */
    public Date getSoCreatedate()
    {
        return soCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.so_createDate
     *
     * @param soCreatedate the value for so_info_sap.so_createDate
     * @mbg.generated
     */
    public void setSoCreatedate(Date soCreatedate)
    {
        this.soCreatedate = soCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sale_org
     *
     * @return the value of so_info_sap.sale_org
     * @mbg.generated
     */
    public String getSaleOrg()
    {
        return saleOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sale_org
     *
     * @param saleOrg the value for so_info_sap.sale_org
     * @mbg.generated
     */
    public void setSaleOrg(String saleOrg)
    {
        this.saleOrg = saleOrg == null ? null : saleOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.dis_c
     *
     * @return the value of so_info_sap.dis_c
     * @mbg.generated
     */
    public String getDisC()
    {
        return disC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.dis_c
     *
     * @param disC the value for so_info_sap.dis_c
     * @mbg.generated
     */
    public void setDisC(String disC)
    {
        this.disC = disC == null ? null : disC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sale_office
     *
     * @return the value of so_info_sap.sale_office
     * @mbg.generated
     */
    public String getSaleOffice()
    {
        return saleOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sale_office
     *
     * @param saleOffice the value for so_info_sap.sale_office
     * @mbg.generated
     */
    public void setSaleOffice(String saleOffice)
    {
        this.saleOffice = saleOffice == null ? null : saleOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.so_overall_status
     *
     * @return the value of so_info_sap.so_overall_status
     * @mbg.generated
     */
    public String getSoOverallStatus()
    {
        return soOverallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.so_overall_status
     *
     * @param soOverallStatus the value for so_info_sap.so_overall_status
     * @mbg.generated
     */
    public void setSoOverallStatus(String soOverallStatus)
    {
        this.soOverallStatus = soOverallStatus == null ? null : soOverallStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.delivery_status
     *
     * @return the value of so_info_sap.delivery_status
     * @mbg.generated
     */
    public String getDeliveryStatus()
    {
        return deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.delivery_status
     *
     * @param deliveryStatus the value for so_info_sap.delivery_status
     * @mbg.generated
     */
    public void setDeliveryStatus(String deliveryStatus)
    {
        this.deliveryStatus = deliveryStatus == null ? null : deliveryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.billing_status
     *
     * @return the value of so_info_sap.billing_status
     * @mbg.generated
     */
    public String getBillingStatus()
    {
        return billingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.billing_status
     *
     * @param billingStatus the value for so_info_sap.billing_status
     * @mbg.generated
     */
    public void setBillingStatus(String billingStatus)
    {
        this.billingStatus = billingStatus == null ? null : billingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sku
     *
     * @return the value of so_info_sap.sku
     * @mbg.generated
     */
    public String getSku()
    {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sku
     *
     * @param sku the value for so_info_sap.sku
     * @mbg.generated
     */
    public void setSku(String sku)
    {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.description
     *
     * @return the value of so_info_sap.description
     * @mbg.generated
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.description
     *
     * @param description the value for so_info_sap.description
     * @mbg.generated
     */
    public void setDescription(String description)
    {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.qty
     *
     * @return the value of so_info_sap.qty
     * @mbg.generated
     */
    public Integer getQty()
    {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.qty
     *
     * @param qty the value for so_info_sap.qty
     * @mbg.generated
     */
    public void setQty(Integer qty)
    {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.unit
     *
     * @return the value of so_info_sap.unit
     * @mbg.generated
     */
    public String getUnit()
    {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.unit
     *
     * @param unit the value for so_info_sap.unit
     * @mbg.generated
     */
    public void setUnit(String unit)
    {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sale_personName
     *
     * @return the value of so_info_sap.sale_personName
     * @mbg.generated
     */
    public String getSalePersonname()
    {
        return salePersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sale_personName
     *
     * @param salePersonname the value for so_info_sap.sale_personName
     * @mbg.generated
     */
    public void setSalePersonname(String salePersonname)
    {
        this.salePersonname = salePersonname == null ? null : salePersonname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sale_personPhone
     *
     * @return the value of so_info_sap.sale_personPhone
     * @mbg.generated
     */
    public String getSalePersonphone()
    {
        return salePersonphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sale_personPhone
     *
     * @param salePersonphone the value for so_info_sap.sale_personPhone
     * @mbg.generated
     */
    public void setSalePersonphone(String salePersonphone)
    {
        this.salePersonphone = salePersonphone == null ? null : salePersonphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sale_personEmail
     *
     * @return the value of so_info_sap.sale_personEmail
     * @mbg.generated
     */
    public String getSalePersonemail()
    {
        return salePersonemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sale_personEmail
     *
     * @param salePersonemail the value for so_info_sap.sale_personEmail
     * @mbg.generated
     */
    public void setSalePersonemail(String salePersonemail)
    {
        this.salePersonemail = salePersonemail == null ? null : salePersonemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sap_CreateBy
     *
     * @return the value of so_info_sap.sap_CreateBy
     * @mbg.generated
     */
    public String getSapCreateby()
    {
        return sapCreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sap_CreateBy
     *
     * @param sapCreateby the value for so_info_sap.sap_CreateBy
     * @mbg.generated
     */
    public void setSapCreateby(String sapCreateby)
    {
        this.sapCreateby = sapCreateby == null ? null : sapCreateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sap_CreaterName
     *
     * @return the value of so_info_sap.sap_CreaterName
     * @mbg.generated
     */
    public String getSapCreatername()
    {
        return sapCreatername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sap_CreaterName
     *
     * @param sapCreatername the value for so_info_sap.sap_CreaterName
     * @mbg.generated
     */
    public void setSapCreatername(String sapCreatername)
    {
        this.sapCreatername = sapCreatername == null ? null : sapCreatername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sap_CreaterTelephone
     *
     * @return the value of so_info_sap.sap_CreaterTelephone
     * @mbg.generated
     */
    public String getSapCreatertelephone()
    {
        return sapCreatertelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sap_CreaterTelephone
     *
     * @param sapCreatertelephone the value for so_info_sap.sap_CreaterTelephone
     * @mbg.generated
     */
    public void setSapCreatertelephone(String sapCreatertelephone)
    {
        this.sapCreatertelephone = sapCreatertelephone == null ? null : sapCreatertelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_sap.sap_CreaterEmail
     *
     * @return the value of so_info_sap.sap_CreaterEmail
     * @mbg.generated
     */
    public String getSapCreateremail()
    {
        return sapCreateremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_sap.sap_CreaterEmail
     *
     * @param sapCreateremail the value for so_info_sap.sap_CreaterEmail
     * @mbg.generated
     */
    public void setSapCreateremail(String sapCreateremail)
    {
        this.sapCreateremail = sapCreateremail == null ? null : sapCreateremail.trim();
    }

    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }
}