package com.bys.ots.model;

public class SoInfoE1Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_e1.SO
     *
     * @mbg.generated
     */
    private String so;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_info_e1.SO_Item
     *
     * @mbg.generated
     */
    private String soItem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_e1.SO
     *
     * @return the value of so_info_e1.SO
     *
     * @mbg.generated
     */
    
    
    public String getSo() {
        return so;
    }

    /**
     * 
     */
    public SoInfoE1Key()
    {
        super();
        // TODO Auto-generated constructor stub
    }

    /**
     * @param so
     * @param soItem
     */
    public SoInfoE1Key(String so, String soItem)
    {
        super();
        this.so = so;
        this.soItem = soItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_e1.SO
     *
     * @param so the value for so_info_e1.SO
     *
     * @mbg.generated
     */
    public void setSo(String so) {
        this.so = so == null ? null : so.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_info_e1.SO_Item
     *
     * @return the value of so_info_e1.SO_Item
     *
     * @mbg.generated
     */
    public String getSoItem() {
        return soItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_info_e1.SO_Item
     *
     * @param soItem the value for so_info_e1.SO_Item
     *
     * @mbg.generated
     */
    public void setSoItem(String soItem) {
        this.soItem = soItem == null ? null : soItem.trim();
    }
}